INSERT INTO PERSON(ID,NAME) VALUES (1001,'ISHAN');
INSERT INTO PERSON(ID,NAME) VALUES (1002,'KANIKA');
INSERT INTO PERSON(ID,NAME) VALUES (1003,'SHEKHAR');
INSERT INTO PERSON(ID,NAME) VALUES (1004,'RISHIKA');
INSERT INTO PERSON(ID,NAME) VALUES (1005,'SALIL');