insert into CURRENCY_EXCHANGE(ID, FROM_CURR, TO_CURR, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (1001,'USD','INR',65.3,'');

insert into CURRENCY_EXCHANGE(ID, FROM_CURR, TO_CURR, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (1002,'EUR','INR',75,'');

insert into CURRENCY_EXCHANGE(ID, FROM_CURR, TO_CURR, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (1003,'AUD','INR',25,'');